config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :users do
    resources :groups
  end

  resources :groups do
    resources :group_memberships, only: :destroy
    resources :expenses
  end

  resources :expenses, except: [:new, :create, :index]

  resources :debts, only: [] do
    member do
      get :settle
    end
  end

  post 'send_invite', to: 'users#send_invite'

end

app/models/group.rb
class Group < ApplicationRecord
  has_many :group_memberships, dependent: :destroy
  has_many :users, through: :group_memberships

  accepts_nested_attributes_for :group_memberships, allow_destroy: true

  has_many :debts
  has_many :expenses, dependent: :destroy

  validates :name, presence: true, uniqueness: true, length: { maximum: 100 }

  def group_memberships_attributes=(group_memberships_attributes)
    existing_user_ids=self.group_memberships.map(&:user_id)
    group_memberships_attributes.each do |i, group_memberships_attribute|
      next if group_memberships_attribute.has_value?("")
      user_id=group_memberships_attribute["user_id"]
      next if existing_user_ids.include?(user_id)
      self.group_memberships.build(group_memberships_attribute)
      existing_user_ids << user_id
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = current_user.groups
  end

  def show
  end

  def new
    @group = current_user.groups.build
    @users = User.all
    (@users.count).times do
      @group.group_memberships.build
    end
  end

  def create
    @group=Group.new(group_params)
    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @users = User.where.not(id: @group.users.pluck(:id))
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to root_path, notice: 'Group was successfully destroyed.'
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    # params.require(:group).permit(:name, :user_ids)
    params.require(:group).permit(:name, group_memberships_attributes: [:user_id, :_destroy])
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg">
  <h1>New Group</h1>

  <%= form_with(model: [current_user, group], local: true) do |form| %>
    <% if @group.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

        <ul>
          <% @group.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-outline mb-4 text-light">
      <%= form.label :name, "Name" %>
      <%= form.text_field :name, class: "form-control" %>
    </div> 

    <% unless group.persisted? %>
      <%= group.id %>
      <h3>Group Members</h3>
      <div id="group_memberships">
        <%= form.fields_for :group_memberships do |user_builder| %>
          <div class="nested-fields">
            <div class="field">
              <%= user_builder.label :user_id, 'Select User: ' %>
              <%= user_builder.collection_select :user_id, @users, :id, :email, { include_blank: true} %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

    <div class="actions">
      <%= form.submit :submit, class: "mb-2 text-light btn btn-dark mt-3" %>
    </div>
  <% end %>

  <% if @group.persisted? %>
    <h3>Current Members</h3>
    <div class="position-relative">
      <% @group.users.each do |user| %>
        <div class="m-3">
          <%= user.email %>
            <%= link_to "Remove", group_group_membership_path(@group, user.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-light btn btn-dark float-lg-end" %>       
        </div>
      <% end %>
    </div>
    <%= link_to 'Back', group_path(@group) %>
  <% else %>
    <%= link_to 'Back', root_path %>
  <% end %>  
</div>

app/views/groups/edit.html.erb
<%= render 'form', group: @group %>

app/views/groups/manage_members.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg">
  <h1>Manage Members for <%= @group.name %></h1>
  <h3>Add Members</h3>
  <%= form_with url: add_members_group_path(@group), method: :post do %>
    <% @users.each do |user| %>
      <% if !(user.groups.include?(@group)) %>
        <div class="m-2">
          <%= check_box_tag "user_ids[]", user.id, @group.users.include?(user) %>
          <%= label_tag user.email %>
        </div>
      <% end %>
    <% end %>
    <div class="actions">
      <%= submit_tag "Add Members", class: "text-light btn btn-sm btn-dark" %>
    </div>
  <% end %>

  <h3>Current Members</h3>
  <ul>
    <% @group.users.each do |user| %>
      <li class="m-2">
        <%= user.email %>
        <%= link_to "Remove", remove_member_group_path(@group, user.id), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-light btn btn-dark" %>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Back', group_path(@group) %>
</div>

app/views/groups/new.html.erb
<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class="container-fluid w-50 shadow mt-5 rounded border p-4 bg">
  <h1><%= @group.name.capitalize %></h1>
  <div>
    <%= link_to 'Edit Group', edit_group_path(@group), class: "text-light btn btn-dark " %>
    <%= link_to 'Destroy Group', @group, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "text-light btn btn-dark" %>
  </div>
  <div>
    <%= link_to 'Back', root_path, class: "text-light btn btn-dark m-2" %>
  </div>
</div>