config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :users do
    resources :groups
  end

  resources :groups do
    resources :group_memberships, only: :destroy
    resources :expenses
  end

  resources :expenses, except: [:new, :create, :index]

  resources :debts, only: [] do
    member do
      get :settle
    end
  end

  post 'send_invite', to: 'users#send_invite'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :group_memberships
  has_many :groups, through: :group_memberships

  has_many :debts, foreign_key: :from_user_id
  has_many :credits, class_name: 'Debt', foreign_key: :to_user_id

  has_many :expenses

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, length: { minimum: 6 }

  def total_borrowed
    debts.where(settled: false).sum(:amount)
  end

  def total_lent
    credits.where(settled: false).sum(:amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  def show
    @total_borrowed = @user.total_borrowed
    @total_lent = @user.total_lent
    @debts = @user.debts
    @credits = @user.credits
  end

  def send_invite
    recipient_email = params[:email]
    InviteNotificationMailer.invite_email(recipient_email, current_user).deliver_now
    redirect_to root_path, notice: 'Invitation to join splitwise sent successfully'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<div class="container-fluid w-75 shadow mt-5 rounded border p-4 bg">
  <h1>Your Account</h1>

  <h6><%= @user.email %></h6>

  <h2>Borrowed Amount</h2>
  <p><%= number_to_currency(@total_borrowed) %></p>

  <h2>Lent Amount</h2>
  <p><%= number_to_currency(@total_lent) %></p>

  <h2>Total expense amount</h2>
  <p><%= Expense.all.sum(&:amount) %></p>

  <h2>Detailed Debts and Credits</h2>
  <table class="table table-bordered border table-dark">
    <thead>
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Amount</th>
        <th>Group</th>
        <th>Expense</th>
        <th>Actions</th>
        <th>Transaction type</th>
      </tr>
    </thead>
    <tbody>
      <% @debts.each do |debt| %>
        <tr>
          <td><%= debt.to_user.email %></td>
          <td><%= debt.from_user.email %></td>
          <td><%= number_to_currency(debt.amount) %></td>
          <td><%= debt.group.name %></td>
          <td><%= debt.expense.description %></td>
          <td>
            <% unless debt.settled %>
              <%= link_to 'Settle', settle_debt_path(debt), method: :patch, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-primary" %>
            <% else %>
              Settled
            <% end %>
          </td>
          <td>You Owe</td>
        </tr>
      <% end %>
      <% @credits.each do |credit| %>
        <tr>
          <td><%= credit.to_user.email %></td>
          <td><%= credit.from_user.email %></td>
          <td><%= number_to_currency(credit.amount) %></td>
          <td><%= credit.group.name %></td>
          <td><%= credit.expense.description %></td>
          <td>
            <% unless credit.settled %>
              <%= link_to 'Settle', settle_debt_path(credit), method: :patch, data: { confirm: 'Are you sure?' } %>
            <% else %>
              Settled
            <% end %>
          </td>
          <td>You lent</td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>