config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :users do
    resources :groups
  end

  resources :groups do
    resources :group_memberships, only: :destroy
    resources :expenses
  end

  resources :expenses, except: [:new, :create, :index]

  resources :debts, only: [] do
    member do
      get :settle
    end
  end

  post 'send_invite', to: 'users#send_invite'

end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-lg py-1 navbar-expand bg navbar-fixed-top">
  <div class="container">
    <%= link_to "Splitwise", root_path, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.email %>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Your Account", edit_user_registration_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "Create a group", new_group_path, class: "dropdown-item" %></li>
            <li><%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>  