config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "home#index"

  resources :users do
    resources :groups
  end

  resources :groups do
    resources :group_memberships, only: :destroy
    resources :expenses
  end

  resources :expenses, except: [:new, :create, :index]

  resources :debts, only: [] do
    member do
      get :settle
    end
  end

  post 'send_invite', to: 'users#send_invite'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="h-100 mh-100 p-0 w-100 d-flex ms-auto justify-content-center" id="center">
  <div class="border-left border-right border-info shadow-sm w-75 d-flex " id="center_bars">
    <%# left sidebar %>
    <div class="position-relative w-25 float-left z-3" id="left_sidebar">
      <div class="text-start overflow-hidden m-2" id="view_links">
        <%= link_to "Debts and Credits", user_path(current_user), class: "d-block text-decoration-none p-2 text-dark border-light" %>
        <div class="tags text-md m-1">
          <div class="header"><%= link_to "Groups", groups_path, class: "position-relative fw-bold fs-3 text-dark text-decoration-none" %>
            <a href="/groups/new" class="float-sm-end text-decoration-none m-2 text-secondary">
              <i class="fa-duotone fa-solid fa-plus"></i>Add
            </a>
          </div>
          <div class="group">
            <% if current_user.groups.any? %>
              <% current_user.groups.each do |group| %>
              <%= link_to group.name, group_expenses_path(group), class: "group-link d-block overflow-hidden text-decoration-none p-2 text-dark border border-light" %>
              <% end %>
            <% end %>
          </div>
        </div>
        <div class="border border-secondary">
          <div class="p-2 border border-secondary" style="background-color: #5bc5a7;">Invite friends</div>
          <%= form_with url: send_invite_path, method: :post do |form| %>
            <div class="row d-flex justify-content-center align-items-center">
              <div class="col-lg m-2">
                <%= form.email_field :email, required: true, class: "form-control", placeholder: "Enter an email" %>
              </div>
              <%= form.submit 'Send Invite', class: "btn btn-md w-75 mb-2 rounded border", style: "background-color: #5bc5a7;" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <%# center column %>
    <div class="position-relative m-2 w-100 border border-light" id="center_bar">
      <div id="center_container"></div>
    </div>
  </div>
</div>